### ISSUE TITLE
Rewrite EP-Routing for "getAllTags" and "getAllDocuments"

### ISSUE THREAD

**Issue by ghost** [ch-a-os/DocSort-Backend#1]
```js
app.get('/getAllDocuments', validateJWT, async (req, res) => res.status(200).send(await Document.find()));
app.get('/getAllTags', validateJWT, async (req, res) => res.status(200).send(await Tag.find()));
```
Should be rewritten into the same format as for example
```js
app.get('/getDocumentFile/:docID', validateJWT, getDocumentFile);
```

**Comment by Mondei1** [comment]
You mean `/getDocumentFile/:docID` returns that one specific document If `ID` is specified and If not, it returns all documents? Same for tags.

**Comment by ghost** [comment]
> You mean `/getDocumentFile/:docID` returns that one specific document If `ID` is specified and If not, it returns all documents? Same for tags.

Nah, i meant to just create a separate function that is called in the EP-route instead of writing the actual execution-logic into the route-register line :)

Moved repo: https://github.com/ch-a-os/DocSort/issues/22
